name: Build

on:
  push:
    branches:
      - "master"
      - "release/*"
    tags:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    uses: UNIwise/workflows/.github/workflows/docker.yaml@master
    secrets: inherit
