name: Lint

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Lint:
    name: lint
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lint with Black
        uses: psf/black@stable